language: ruby
rvm:
- 2.4.1
before_script:
- psql -c 'create database rails_survey_widget_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bin/rake
deploy:
  provider: heroku
  api_key:
    secure: gBqaaX595pHXVCdFCNgv4PL1C4ciOgKcccqVGXfHqoxTEoCiHoOTulECwzQrx5LOINtE1lkPzEfRVD3b9eP5EFCHhBzPdXk0JSnXo2cTXqcrbcnAXUjx3/Krmv78NKY+p581Yi0QDgHvwec7aoa2UxqVHc1mrDZfj+0jIDMrUiej1fJzASYD2T1ZFYVePioNynifbj05oByhXysAI+hHPdZNz6RM2QtnQSz3xPIZy/IXo9EbgHtJjI39/NFAFnt3G1bVrnEefOxAZhSAee5lUKTMGy3nKwL1BDuTcaqWM2fVAfKATgVFLt3oW209aB45L8UAmsRuk9F+9HO43O6QT11uZv9XMj0mLp9Ft+sOP1FdJ6DT4qACvfXNTPHyMO/aovZzz+S8AOqSHz8vxU4aHsulyrbOnKMAIdEO9NtnyV5TfkF/h+krl722vvp3nxvHD+sI0iuFDoX6AVz6qY5MxQJJcxblxSy6JEChrAPu3eJPsz8N7f4GmRXHJHB0llhCaMKk9wSlutehHoxU5BlvyKD4EJeuM7gGOTpZ7rak7/OQZ0XxMWbiGtGNA3bfKHe/nQMyGlLu732LOa3NPH950n3cEaNlPjU1lE3/T22/ykylkbeeKhELBJG84h4RE721RrKRJIEE1TznBolA7JcMPz7pzl84ZdFQe+ElR+x8Qjk=
  app: young-refuge-23666
  on:
    repo: misternu/rails_survey_widget
