language: ruby
rvm:
- 2.4.1
before_script:
- psql -c 'create database rails_survey_widget_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bin/rake
deploy:
  provider: heroku
  api_key:
    secure: mH/lxTzubNW2E3seyGPnU7erbYHbP1e8oh7oe74a8opDuW02MlW+DJV/1RlXJPQQUibIJaQmvisCCrdvyyMOUacQ9g9m6uLFTjnSUkd4jj0Y6hP8EcekhFgV45+ZAqoHXMbgOw+q2zf7VPuDa8+nodEEXNMfR96Q94kacMI7II+ejjGVEfY7gvQpWHjGfPk1fTZgQF5oG2bNDCozmKhSuEtCp+5xELF1oL9Gj8bInDeD3andf928AvJFgKxWEBCMWy7lyx/32DMmc8xjFONl1LLgsXDEayW7BoPjaqyg3KHW3GRZgQbRUZ7shs+YhM3srqgNpRPf6jgCx9Eptx1Ku6pq0b7fKs9iSfIWRDNOLu5Mfd9j4ANQrZK7y3le6wMt8TrEonS9SOl05W3G5ksC0AbwuwrDqyWj4dtfeb7SkVTxBn+WegcsXUVqJ89ZF8zJzANKcFX2VNbJjp3ifoNWE3fHaX/G12Sy/o9/0mO/Q+6Cav7MYpbmspYAg6P7ec7FpI74eLhYeVxCDtbJoS/fbGJBN7mJIYTHDMunC5O83kk3KV+3pBCXWWDJsWsQ+i9G/rURmKFvnaETWJ+N+gRFCMD62WeGBQxZjBKuXlrgCALtmECGMldMuCCtRvhRhjk/wapE074ZFcB53Q1EGcvDgSSC+zjEL8p/KkZTQ/HqGAY=
  app: rails-survey-widget
  on:
    repo: misternu/rails_survey_widget
